12/config/routes.rb
Rails.application.routes.draw do
  resources :short_urls
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root "short_urls#index"

  get '*path', to: 'short_urls#redirect'
end

12/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

12/app/models/short_url.rb
class ShortUrl < ApplicationRecord
end

12/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

12/app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :set_short_url, only: %i[ show edit update destroy ]

  # GET /short_urls or /short_urls.json
  def index
    @short_urls = ShortUrl.all
  end

  # GET /short_urls/1 or /short_urls/1.json
  def show
  end

  def redirect
    @short_url = ShortUrl.find_by(hash_key: request.path[1..-1])
    if @short_url
      redirect_to @short_url.long_url, allow_other_host: true
    else
      redirect_to "/404"
    end
  end

  # GET /short_urls/new
  def new
    @short_url = ShortUrl.new
  end

  # GET /short_urls/1/edit
  def edit
  end

  # POST /short_urls or /short_urls.json
  def create
    @short_url = ShortUrl.new(short_url_params)

    respond_to do |format|
      if @short_url.save
        format.html { redirect_to short_url_url(@short_url), notice: "Short url was successfully created." }
        format.json { render :show, status: :created, location: @short_url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /short_urls/1 or /short_urls/1.json
  def update
    respond_to do |format|
      if @short_url.update(short_url_params)
        format.html { redirect_to short_url_url(@short_url), notice: "Short url was successfully updated." }
        format.json { render :show, status: :ok, location: @short_url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /short_urls/1 or /short_urls/1.json
  def destroy
    @short_url.destroy!

    respond_to do |format|
      format.html { redirect_to short_urls_url, notice: "Short url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_url
      @short_url = ShortUrl.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def short_url_params
      params.require(:short_url).permit(:long_url, :hash_key)
    end
end

12/app/helpers/application_helper.rb
module ApplicationHelper
end

12/app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

12/app/views/short_urls/_form.html.erb
<%= form_with(model: short_url) do |form| %>
  <% if short_url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(short_url.errors.count, "error") %> prohibited this short_url from being saved:</h2>

      <ul>
        <% short_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :long_url, style: "display: block" %>
    <%= form.text_field :long_url, type: "url", placeholder: "https://example.com", pattern: "https://.*" %>
  </div>

  <div>
    <%= form.label "Custom Key", style: "display: block" %>
    <%= form.text_field :hash_key %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

12/app/views/short_urls/_short_url.html.erb
<div id="<%= dom_id short_url %>">
  <p>
    <strong>Long url:</strong>
    <%= short_url.long_url %>
  </p>

  <p>
    <strong>Custom Url:</strong>
    <%= short_url.hash_key %>
  </p>
  <%= link_to "Test this url", short_url.long_url %>
</div>

12/app/views/short_urls/edit.html.erb
<h1>Editing short url</h1>

<%= render "form", short_url: @short_url %>

<br>

<div>
  <%= link_to "Show this short url", @short_url %> |
  <%= link_to "Back to short urls", short_urls_path %>
</div>

12/app/views/short_urls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Short urls</h1>

<div id="short_urls">
  <% @short_urls.each do |short_url| %>
    <%= render short_url %>
    <p>
      <%= link_to "Show this short url", short_url %>
    </p>
  <% end %>
</div>

<%= link_to "New short url", new_short_url_path %>

12/app/views/short_urls/new.html.erb
<h1>New short url</h1>

<%= render "form", short_url: @short_url %>

<br>

<div>
  <%= link_to "Back to short urls", short_urls_path %>
</div>

12/app/views/short_urls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @short_url %>

<div>
  <%= link_to "Edit this short url", edit_short_url_path(@short_url) %> |
  <%= link_to "Back to short urls", short_urls_path %>

  <%= button_to "Destroy this short url", @short_url, method: :delete %>
</div>
`